### ISSUE TITLE
ice6/osmd  demo operation - not work with dropped file

### ISSUE THREAD

**Issue by AlbertHart** [AlbertHart/osmd_transpose#12]
I was trying to test transposing in:

https://ice6.github.io/opensheetmusicdisplay/build/

But I ran into two problems.

![image](https://user-images.githubusercontent.com/8965352/82228297-30fcdf00-98e6-11ea-9588-043c6a1bcb41.png)

and 

![image](https://user-images.githubusercontent.com/8965352/82228454-60abe700-98e6-11ea-8ef8-a88c25b4d40a.png)

**Comment by ice6** [comment]
@AlbertHart 

thanks for the detailed description.

the two problems had been solved.

[https://ice6.github.io/opensheetmusicdisplay/build/](https://ice6.github.io/opensheetmusicdisplay/build/)
